---
micronaut:
  application:
    name: micronaut
  executors:
    io:
      type: fixed
      nThreads: 75

cassandra:
  keyspace: ks1
  secure-connect-bundle: ../../compare/secure-connect-framework-compare.zip
  username: datastax
  password: datastax
