---
micronaut:
  application:
    name: micronaut

---
datasources:
  default:
    url: "jdbc:postgresql://postgres:5432/postgres"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

