---
version: '3'
services:
  spring:
    build:
      context: ../spring/
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  spring-driver:
    build:
      context: ../spring-driver/
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-mapper:
    build:
      context: ../micronaut-mapper/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-mapper-graal:
    build:
      context: ../micronaut-mapper/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-driver:
    build:
      context: ../micronaut-driver/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-driver-graal:
    build:
      context: ../micronaut-driver/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-mapper-fixed-thread-pool:
    build:
      context: ../micronaut-mapper-fixed-thread-pool/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-mapper-fixed-thread-pool-graal:
    build:
      context: ../micronaut-mapper-fixed-thread-pool/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-driver-fixed-thread-pool:
    build:
      context: ../micronaut-driver-fixed-thread-pool/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-driver-fixed-thread-pool-graal:
    build:
      context: ../micronaut-driver-fixed-thread-pool/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  helidon-mp:
    build:
      context: ../helidon-mp/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  quarkus:
    build:
      context: ../quarkus/
      dockerfile: src/main/docker/Dockerfile.jvm
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  quarkus-graal:
    build:
      context: ../quarkus/
      dockerfile: src/main/docker/Dockerfile.native
    volumes:
      - ${ASTRA_DB_BUNDLE}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"