---
version: '3'
services:
  spring:
    build:
      context: ../spring/
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  spring-jdbc:
    build:
      context: ../spring-jdbc/
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jpa:
    build:
      context: ../micronaut-jpa/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jpa-graal:
    build:
      context: ../micronaut-jpa/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jdbc:
    build:
      context: ../micronaut-jdbc/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jdbc-graal:
    build:
      context: ../micronaut-jdbc/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jpa-fixed-thread-pool:
    build:
      context: ../micronaut-jpa-fixed-thread-pool/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jpa-fixed-thread-pool-graal:
    build:
      context: ../micronaut-jpa-fixed-thread-pool/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jdbc-fixed-thread-pool:
    build:
      context: ../micronaut-jdbc-fixed-thread-pool/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  micronaut-jdbc-fixed-thread-pool-graal:
    build:
      context: ../micronaut-jdbc-fixed-thread-pool/
      dockerfile: Dockerfile.native
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  helidon-mp:
    build:
      context: ../helidon-mp/
      dockerfile: Dockerfile.jvm
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  quarkus:
    build:
      context: ../quarkus/
      dockerfile: src/main/docker/Dockerfile.jvm
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"
  quarkus-graal:
    build:
      context: ../quarkus/
      dockerfile: src/main/docker/Dockerfile.native
    volumes:
      - ${ASTRA_PATH}:/var/secure-connect-framework-compare.zip
    ports:
      - "8080:8080"